apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.name" . }}
  labels:
    {{ include "chart.labels" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "backend.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "backend.name" . }}
    spec:
      containers:
      - name: {{ include "backend.name" . }}
        image: "ghcr.io/thedatasnok/fullstack-demo-backend:{{ .Values.version }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
