apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.name" . }}
  labels:
    {{ include "chart.labels" . }}
spec:
  selector:
    app: {{ include "backend.name" . }}
  ports:
    - port: 8080
      targetPort: 8080
