apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.name" . }}
  labels:
    {{ include "chart.labels" . }}
spec:
  selector:
    app: {{ include "frontend.name" . }}
  ports:
    - port: 80
      targetPort: 80
