name: Release to GitHub

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-push-backend:
    name: Build and push backend docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: gradle :apps:backend:jib --image=ghcr.io/thedatasnok/fullstack-demo-backend:latest

      - run: gradle :apps:backend:jib --image=ghcr.io/thedatasnok/fullstack-demo-backend:${{ github.ref_name }}


  build-push-frontend:
    name: Build and push frontend docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: apps/frontend
          push: true
          tags: |
            ghcr.io/thedatasnok/fullstack-demo-frontend:latest
            ghcr.io/thedatasnok/fullstack-demo-frontend:${{ github.ref_name }}


  # TODO: uncomment whenever app module is defined properly
  # deploy-stack:
  #   name: Deploy stack to staging
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - build-push-backend
  #     - build-push-frontend
  #   environment: staging
  #   steps:
  #     - uses: actions/checkout@v3

  #     - run: cd infrastructure

  #     - uses: hashicorp/setup-terraform@v2

  #     - run: terraform apply -target=module.app -var="environment_name=${{ var.ENVIRONMENT_NAME }},environment_url=${{ var.ENVIRONMENT_URL }}"

